### PR TITLE
fix batch

### LINKED ISSUE #12: [BUG] batching does not batch
**Describe the bug**
While configuring s3 parquet sink with batching, I find out that the sinks creates a separate file for each record.

**To Reproduce**
1. create a parquet/avro s3 sink with batching 
2. send 2 messages
3. see that there are 2 parquet files on s3

**Expected behavior**
1 file parquet file containing 2 records

**Proposed solution**
from the code it seems that the batching is done wrong. we should batch 'plain' GenericRecords on the 'write' function, and later on the 'flush' function we should group records with by schema and partition path, change the 'Format.recordWriter' to take a list of records and only then send it to the blob store.

Side note:
In general a lot of sinks need some kind of windowing, is there any way to configure the window properties of pulsar function to work with pulsar sink? I think it could be useful to have another api for the sink that would get a collection of records rather than 1 record at a time. this way we do not need to reimplement batching for each sink

EDIT: is there a way to open PR with a fix?

@codelipenghui @jianyun8023

### PR DESCRIPTION
**Pull request by jianyun8023**
fixed #12

### CODE REVIEW

File: src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java [hunk 1]
```diff
@@ -144,31 +145,27 @@ public void close() throws Exception {
...
-            incomingList.add(Pair.of(record, blob));
+            incomingList.add(record);
             currentSize = incomingList.size();
         } finally {
             rwlock.writeLock().unlock();
         }
         LOGGER.info("build blob success[recordSequence={}]", sequenceId);
         if (currentSize == sinkConfig.getBatchSize()) {
-            flushExecutor.submit(() -> flush());
+            flushExecutor.submit(this::flush);
```
Comment (codelipenghui) [inline src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java:158]: I noticed the default batch size is 10, which will result in write a parquet file for every 10 messages?

**Review by codelipenghui — CHANGES_REQUESTED** [review]

File: src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java [hunk 2]
```diff
@@ -179,32 +176,42 @@ private void flush() {
...
-                blobPair.getLeft().fail();
-                iter.remove();
-            }
+        Record<GenericRecord> firstRecord = recordsToInsert.get(0);
+        Schema<GenericRecord> schema = getPulsarSchema(firstRecord);
+        format.initSchema(schema);
+
+        final Iterator<Record<GenericRecord>> iter = recordsToInsert.iterator();
+        try {
+            String filepath = buildPartitionPath(firstRecord, partitioner, format);
```
Comment (freeznet) [inline src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java:185]: why use `firstRecord` to get the `filepath`? what if batch messages with different partition path? like if we have a time based partitioner with hours, and a batch message contains messages from 00:59 ~ 01:01, shouldn't the messages be separated into two partition file?

File: src/test/java/org/apache/pulsar/io/jcloud/format/FormatTest.java [hunk 3]
```diff
@@ -30,12 +29,12 @@
...
     @Test
     public void testGetExtension() {
-        AvroFormat<BlobStoreAbstractConfig> avroFormat = new AvroFormat<>();
+        AvroFormat avroFormat = new AvroFormat();
         Assert.assertEquals(avroFormat.getExtension(), ".avro");
     }
 
     public void testRecordWriter() {
-        AvroFormat<BlobStoreAbstractConfig> avroFormat = new AvroFormat<>();
+        AvroFormat avroFormat = new AvroFormat();
```
Comment (freeznet) [inline src/test/java/org/apache/pulsar/io/jcloud/format/FormatTest.java:37]: seems the test is not complete?

**Review by freeznet — COMMENTED** [review]
I have got some questions, PTAL, thanks.

File: src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java [hunk 4]
```diff
@@ -179,32 +176,42 @@ private void flush() {
...
-                blobPair.getLeft().ack();
-                log.info("write success {}", blobPair.getLeft().getRecordSequence().get());
-            } catch (ContainerNotFoundException e) {
-                log.error("Bad message", e);
-                blobPair.getLeft().fail();
-                iter.remove();
-            }
+        Record<GenericRecord> firstRecord = recordsToInsert.get(0);
+        Schema<GenericRecord> schema = getPulsarSchema(firstRecord);
+        format.initSchema(schema);
```
[the remark this answers is not in the document]
Comment (jianyun8023) [reply src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java:181]: Yes, if fields are added, this may cause the new fields to be lost. If you do not initialize the schema at the beginning, let each record use its own schema, this will involve schema conversion and the problem of indeterminability of the parquet data format.

Of course, I can increase the schema version check. If the version changes, the current file will only be written here, and the data of the new schema will be output next time.

File: src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java [hunk 5]
```diff
@@ -144,31 +145,27 @@ public void close() throws Exception {
...
     }
 
     private void flush() {
-        final List<Pair<Record<GenericRecord>, Blob>> recordsToInsert;
+        final List<Record<GenericRecord>> recordsToInsert;
 
+        if (incomingList.isEmpty()) {
+            log.info("no pending data...");
+            return;
+        }
```
[the remark this answers is not in the document]
Comment (jianyun8023) [reply src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java:168]: ok.

File: src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java (hunk 1 above)
Comment (jianyun8023) [reply src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java:158]: Is such that.

File: src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java (hunk 2 above)
Comment (jianyun8023) [reply src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java:185]: Since the file is written once, the data needs to be divided into sections. For example, when writing by time, the time is used as the path, and the file name is the unique id of the first message of each batch of messages.
example：
`2021/05/18/17/0099887.json`
